version: '3.8'

services:
  frontend:
    build: .
    env_file: .env
    ports:
      - "5173:80"
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend

  db-init:
    image: ghcr.io/celuma/celuma-backend:latest
    pull_policy: always
    env_file: .env
    command: bash init_db.sh
    depends_on:
      - db
    restart: "no"

  backend:
    image: ghcr.io/celuma/celuma-backend:latest
    pull_policy: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db-init
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celumadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:


